version: "3.7"
services:
  webapp:
    image: junkkari/webapp
    deploy: 
      # placement:
      #   constraints: [node.role == worker]
      restart_policy:
        condition: any
    ports:
      - "80:80"
