version: "3.7"
services:
  postgres:
    image: junkkari/possu
    volumes:
      # Store Postgres data on host's filesystem in `~/postgres/data`,
      # in order to avoid it being wiped out when container is redeployed.
      - "postgres-data:/var/lib/postgresql/data"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    ports:
      - "5432:5432"
  webapp:
    image: junkkari/webapp
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=postgres
volumes:
  postgres-data:
